language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - "/^v[0-9]+\\.[0-9]+/"

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml

env:
  global:
  # travis encrypt BINTRAY_USER=[username]
  - secure: WKihORyQcKmgbRfG4Te/QA3rIcUJUx2wPOglydiTYb2GnfuoV+3O1tKRUjXZykn4RaPOWsvMhmJrev61GoiEatbQho4c2roUKg6JeHsLQC+yr2NggppZ1Gt/eVnoJRUq3alHFFb1k4dxpqud1gq9Bfrgz6Egh4oPD/sR6oN/BGVm+9XocWsF64WRevkION6agVlxmUG+hXCGK1CK9Axk9F0hMV1nExEnNRUSZdRO+74dFsVANMqDidtQhqTU5Fd6HLH4EkbL4ABIYpt0ruq2bqwznCwwvZHnPNEcRpnvPf7VHIhh72qdMbZrSfclUkhBQ7v5YMPaAu4WDmQGXpyQXGg6Mqq2KQYE8dfh20yvk71Q3TSLwJ1k5CSrFjf58/y7co+ZgCn/5H59xYx/pTuH7LItBy0gcsQI6b+Fs6u375Cdf/sAyrX7sXA1Jg+deIPgQSy+pu5Q6Ak8iIcXh48Vdy8C3cJ3J4CfZ1q0vrYW03SEd8jc2vzFquh6WGly69Y69gaBUY7c94zeGJt2c2/v+T8DHc4/QoyhNCtxrLvhZy6lelvPl7P98uOPUXAsNWmebvT1qHsVw6wAz75wSCYrxVdx9NCs7ZIZHovwQY7/JE7u6zM7q3PvIYeaXmqzqbQ5skrGqLaI+SVrIzB3LbNHuIkxcvWndTtv1yaKAAmJ6J0=
  # travis encrypt BINTRAY_API_KEY=[api key]
  - secure: R4gX32IQmclYyKgAum8xLVOOG0AeDQy+54LJqTIvAGghkPbjOEUJlLR9qmTulKgfeZwxugVU+m+DUPBaDlbNdnZhUic1cTb6rbx/wFFbmmAl8WEKMnkI+cVOMnP29r1cdXSVek5yQ6QwYnUMuMp79036+LJBD7YHh/pdVAjKoW8XGxw/MRY8QKehBeWEhF90C2GiVg7PeBr/QO2n4ODKt0I8WGkwJDyV3Gs7NR1isZdJL+Q+pEEcXZ1dtv4do+xY4IP4zptssKsvn0snJPXZ0BdQa/uHrVf7PR3AvtceNJvhboL5vwjwVQAGcNBwtpGSx2JmBjwjeeUt3lwC6523DUJ00RFRIXbOypKKZ6+FyEYcqLPobU94pDU+qjs3BB4OYqiFf86kxJNuP7phisxTz1g+/Z3Gk7nno1peydUYkE1Fy+OwqH4qz3JTrg6WydL/3gJZHXMtUkOYYyIGZd9DW+EmGaEyvenZNwgyh4TecIXtyYltrmMqBdGmmcilkMcK+mepu1I/f2Hmzqv5oVYmhibZO9GiQOfjAc2FRhxLOHnOP/yhhc1SblavSU7v0pw0e1loaWPCAPXge2nsqmNUr3NIAFlr+krqXR2k1Ta97iIwM8nOxoU0b5+70TL6VyGsh8kEeISpNoRsbcabMHwWvhtM3FcLciZgzifAvqV1gD8=
